import { router } from "expo-router";
import { useEffect, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { Image } from "expo-image";
import { useAnirakuAuth } from "@/providers/auth-provider";
import { useBookmarks } from "@/hooks/use-bookmarks";
import { useNotifications } from "@/hooks/use-notifications";
import { useWatchHistory } from "@/hooks/use-watch-history";
import { EmptyState, ErrorState, LoadingState } from "@/components/async-state";
import { AppIcon } from "@/components/app-icon";
import { AnirakuMark, DotLabel, nothing, Signal } from "@/components/nothing-ui";
import { NativeScreen } from "@/components/screen";

type LibraryTab = "history" | "bookmarks" | "alerts";
const tabMeta: Record<LibraryTab, { label: string; icon: "history" | "bookmark-multiple-outline" | "bell-outline" }> = { history: { label: "History", icon: "history" }, bookmarks: { label: "Saved", icon: "bookmark-multiple-outline" }, alerts: { label: "Alerts", icon: "bell-outline" } };

export default function LibraryScreen() {
  const auth = useAnirakuAuth();
  const history = useWatchHistory();
  const bookmarks = useBookmarks();
  const notifications = useNotifications();
  const [tab, setTab] = useState<LibraryTab>("history");
  useEffect(() => {
    if (!auth.loading && !auth.user) router.replace("/auth" as never);
  }, [auth.loading, auth.user]);
  if (auth.loading || !auth.user) return <NativeScreen scroll={false} style={styles.fill}><View style={styles.redirectState}><DotLabel>ACCOUNT REQUIRED</DotLabel><Text style={styles.redirectTitle}>Opening your secure library</Text><Text style={styles.redirectCopy}>Your history, saved titles, and alerts are synced to your verified Aniraku account.</Text></View></NativeScreen>;
  const data = tab === "history" ? history.history : tab === "bookmarks" ? bookmarks.bookmarks : notifications.notifications;
  const records = data.data ?? [];
  const content = data.isPending ? <LoadingState label="Synchronizing your library" /> : data.isError ? <ErrorState message="Your library could not be synchronized." onRetry={() => void data.refetch()} /> : records.length === 0 ? <EmptyState label={tab === "history" ? "Watch a title to begin your synchronized history." : tab === "bookmarks" ? "Save a title to begin your synchronized bookmarks." : "No account notifications yet."} /> : <FlatList data={records} keyExtractor={(item) => item.id ?? `${item.anime_id}:${item.episode_number}`} contentContainerStyle={styles.list} renderItem={({ item }) => tab === "history" ? <Pressable accessibilityRole="button" onPress={() => router.push({ pathname: "/watch/[id]", params: { id: String(item.anime_id), episode: String(item.episode_number), title: item.anime_title ?? "Anime", image: item.anime_image ?? "" } } as never)} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><Image source={{ uri: item.anime_image || "" }} style={styles.thumb} contentFit="cover" transition={0} cachePolicy="memory-disk" /><View style={styles.rowBody}><Signal label={`EP ${item.episode_number}`} tone="live" /><Text style={styles.rowTitle} numberOfLines={1}>{item.anime_title || "Anime"}</Text><View style={styles.progressTrack}><View style={[styles.progress, { width: `${Math.min(100, Math.round((item.progress / Math.max(item.duration, 1)) * 100))}%` }]} /></View><Text style={styles.rowMeta}>{Math.round((item.progress / Math.max(item.duration, 1)) * 100)}% WATCHED · RESUME</Text></View><AppIcon name="chevron-right" size={20} color={nothing.muted} /></Pressable> : tab === "bookmarks" ? <Pressable accessibilityRole="button" onPress={() => router.push((`/anime/${item.anime_id}`) as never)} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><Image source={{ uri: item.image || "" }} style={styles.thumb} contentFit="cover" transition={0} cachePolicy="memory-disk" /><View style={styles.rowBody}><Signal label={item.type || "ANIME"} /><Text style={styles.rowTitle} numberOfLines={2}>{item.title || "Anime"}</Text><Text style={styles.rowMeta}>SAVED TO LIBRARY</Text></View><AppIcon name="chevron-right" size={20} color={nothing.muted} /></Pressable> : <Pressable accessibilityRole="button" onPress={() => { void notifications.markRead.mutateAsync(item.id); if (item.anime_id) router.push((`/anime/${item.anime_id}`) as never); }} style={({ pressed }) => [styles.alert, pressed && styles.pressed]}><Signal label={item.read ? "READ" : item.type?.toUpperCase() || "INFO"} tone={item.read ? "muted" : "live"} /><Text style={styles.alertText}>{item.message}</Text>{!item.read ? <View style={styles.unread} /> : null}</Pressable>}/>;
  const current = tabMeta[tab];
  return <NativeScreen scroll={false} style={styles.fill}><View style={styles.top}><Pressable accessibilityRole="button" accessibilityLabel="Close library" onPress={() => router.back()} style={styles.close}><AppIcon name="arrow-left" size={21} color={nothing.white} /></Pressable><View style={styles.titleBlock}><DotLabel>LIBRARY / VERIFIED SYNC</DotLabel><Text style={styles.title}>Your collection</Text></View><AnirakuMark size={36} /></View><View style={styles.tabs}>{(["history", "bookmarks", "alerts"] as LibraryTab[]).map((item) => <Pressable accessibilityRole="tab" accessibilityState={{ selected: tab === item }} key={item} onPress={() => setTab(item)} style={[styles.tab, tab === item && styles.tabActive]}><AppIcon name={tabMeta[item].icon} size={17} color={tab === item ? nothing.black : nothing.muted} /><Text style={[styles.tabText, tab === item && styles.tabTextActive]}>{tabMeta[item].label}</Text></Pressable>)}</View><View style={styles.sectionHead}><View><DotLabel tone="live">{current.label.toUpperCase()}</DotLabel><Text style={styles.sectionTitle}>{current.label === "History" ? "Pick up where you left off" : current.label === "Saved" ? "Your locked signals" : "Library activity"}</Text></View><Text style={styles.count}>{String(records.length).padStart(2, "0")}</Text></View><View style={styles.content}>{content}</View></NativeScreen>;
}

const styles = StyleSheet.create({
  fill: { flex: 1 }, redirectState: { flex: 1, paddingHorizontal: 24, justifyContent: "center", gap: 9 }, redirectTitle: { color: nothing.white, fontSize: 24, fontWeight: "900", letterSpacing: -0.6 }, redirectCopy: { color: nothing.muted, fontSize: 13, lineHeight: 19, maxWidth: 290 }, top: { minHeight: 82, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", gap: 10 }, close: { width: 42, height: 42, borderRadius: 14, borderWidth: 1, borderColor: nothing.line, backgroundColor: nothing.raised, alignItems: "center", justifyContent: "center" }, titleBlock: { flex: 1, gap: 2 }, title: { color: nothing.white, fontSize: 24, fontWeight: "900", letterSpacing: -0.65 }, tabs: { flexDirection: "row", marginHorizontal: 16, gap: 7, padding: 5, borderRadius: 15, backgroundColor: nothing.surface, borderWidth: 1, borderColor: nothing.line }, tab: { flex: 1, minHeight: 37, flexDirection: "row", gap: 5, justifyContent: "center", alignItems: "center", borderRadius: 10 }, tabActive: { backgroundColor: nothing.white }, tabText: { color: nothing.muted, fontFamily: "monospace", fontWeight: "900", fontSize: 8, letterSpacing: 0.2 }, tabTextActive: { color: nothing.black }, sectionHead: { minHeight: 74, marginHorizontal: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, sectionTitle: { color: nothing.white, marginTop: 4, fontSize: 18, fontWeight: "900", letterSpacing: -0.4 }, count: { color: nothing.dim, fontFamily: "monospace", fontWeight: "900", fontSize: 12 }, content: { flex: 1 }, list: { paddingHorizontal: 16, paddingBottom: 30, gap: 9 }, row: { minHeight: 100, padding: 9, flexDirection: "row", alignItems: "center", gap: 11, borderRadius: 16, backgroundColor: nothing.surface, borderWidth: 1, borderColor: nothing.line }, thumb: { width: 57, height: 82, borderRadius: 10, backgroundColor: nothing.raised }, rowBody: { flex: 1, justifyContent: "center", gap: 5 }, rowTitle: { color: nothing.white, fontWeight: "900", fontSize: 14, lineHeight: 18 }, rowMeta: { color: nothing.dim, fontFamily: "monospace", fontSize: 8, fontWeight: "800", letterSpacing: 0.35 }, progressTrack: { height: 3, overflow: "hidden", borderRadius: 2, backgroundColor: nothing.line }, progress: { height: "100%", backgroundColor: nothing.green }, alert: { minHeight: 88, padding: 14, gap: 8, borderRadius: 16, backgroundColor: nothing.surface, borderWidth: 1, borderColor: nothing.line }, alertText: { color: nothing.white, fontSize: 13, lineHeight: 19 }, unread: { width: 7, height: 7, borderRadius: 99, backgroundColor: nothing.green, position: "absolute", top: 13, right: 13 }, pressed: { opacity: 0.75, transform: [{ scale: 0.985 }] },
});
