import { StyleSheet, Text, type StyleProp, type TextStyle } from "react-native";

const glyphs: Record<string, string> = {
  "home": "⌂",
  "home-variant-outline": "⌂",
  "view-grid-outline": "▦",
  "calendar": "▣",
  "calendar-blank-outline": "▣",
  "shuffle-variant": "↔",
  "account": "◎",
  "account-circle-outline": "◎",
  "circle-outline": "○",
  magnify: "⌕",
  "arrow-left": "←",
  "rewind-10": "↶",
  pause: "Ⅱ",
  play: "▶",
  "fast-forward-10": "↷",
  "skip-next": "⏭",
  bell: "🔔",
  "bell-outline": "🔔",
  bookmark: "◆",
  "bookmark-multiple-outline": "◆◆",
  eye: "◉",
  "eye-outline": "◉",
  "eye-off-outline": "◎",
  fire: "🔥",
  heart: "♥",
  "heart-outline": "♡",
  "cog-outline": "⚙",
  download: "↓",
  refresh: "↻",
  "tune-variant": "☰",
  "trash-can-outline": "✕",
  "delete-forever-outline": "✕",
  logout: "←",
  "cellphone-arrow-down": "↓",
  information: "ℹ",
  "file-document-outline": "≡",
  "clock-counter": "◷",
  "clock-outline": "◷",
  reply: "↩",
  "reply-outline": "↩",
  "account-edit-outline": "⚙",
  sleep: "☽",
  send: "↑",
  "share-variant": "↗",
  "open-in-new": "↗",
  "link-variant": "🔗",
  "content-copy": "⧉",
  close: "✕",
  "arrow-top-right": "↗",
  "chevron-left": "‹",
  "chevron-right": "›",
  "chevron-up": "‹",
  "chevron-down": "›",
  "movie-open-outline": "🎬",
  "cloud-offline-outline": "☁",
  "play-circle": "▶",
  "play-circle-outline": "▶",
};

export function AppIcon({ name, size = 20, color, style }: { name: string; size?: number; color: string; style?: StyleProp<TextStyle> }) {
  return <Text accessibilityElementsHidden style={[styles.icon, { color, fontSize: size, lineHeight: size + 2 }, style]}>{glyphs[name] ?? "•"}</Text>;
}

const styles = StyleSheet.create({ icon: { fontFamily: "SpaceGrotesk-Regular", fontWeight: "700", includeFontPadding: false, textAlign: "center" } });
