import { StyleSheet } from "react-native";
import { nothing } from "@/components/nothing-ui";

export const chrome = StyleSheet.create({
  controlsBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 10,
    justifyContent: "space-between",
    backgroundColor: "rgba(0,0,0,0.42)",
    paddingHorizontal: 8,
    paddingTop: 6,
    paddingBottom: 5,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  topBtn: {
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 4,
  },
  topTitle: {
    flex: 1,
    color: "#FFF",
    fontSize: 14,
    lineHeight: 16,
    marginLeft: 4,
    marginRight: 4,
  },
  topActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  serverPill: {
    backgroundColor: nothing.red,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 4,
    marginLeft: 2,
  },
  serverPillText: {
    color: nothing.black,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  bottomDeck: {
    gap: 4,
  },
  pillRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 6,
  },
  resumePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(9,9,9,0.8)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  resumePillText: {
    color: "#FFF",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  skipPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: nothing.red,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 4,
  },
  skipPillText: {
    color: "#FFF",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  timelineRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  timeText: {
    color: "#FFF",
    fontSize: 11,
    fontWeight: "600",
    minWidth: 34,
    textAlign: "center",
    fontVariant: ["tabular-nums"],
  },
  timelineTrack: {
    flex: 1,
    height: 14,
    justifyContent: "center",
  },
  timelineBuffered: {
    position: "absolute",
    left: 0,
    height: 2,
    borderRadius: 1,
    backgroundColor: "rgba(255,255,255,0.35)",
  },
  timelinePlayed: {
    position: "absolute",
    left: 0,
    height: 2,
    borderRadius: 1,
    backgroundColor: nothing.red,
  },
  timelineKnob: {
    position: "absolute",
    top: 2,
    width: 10,
    height: 10,
    marginLeft: -5,
    borderRadius: 5,
    backgroundColor: "#FFF",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
  },
  actionRail: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  railSide: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    minWidth: 72,
  },
  railSideRight: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 2,
    minWidth: 72,
  },
  railCenter: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  railBtn: {
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 4,
  },
  railBtnDisabled: {
    opacity: 0.3,
  },
  playFab: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#FFF",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 3,
    elevation: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  lockedOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  lockedPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(0,0,0,0.7)",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  lockedPillText: {
    color: "#FFF",
    fontSize: 12,
    fontWeight: "600",
  },
  badge2x: {
    position: "absolute",
    top: 16,
    alignSelf: "center",
    zIndex: 15,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "rgba(0,0,0,0.75)",
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 8,
  },
  badge2xText: {
    color: "#FFF",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  verticalBarWrap: {
    position: "absolute",
    right: 12,
    top: "20%",
    bottom: "25%",
    zIndex: 15,
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 4,
  },
  verticalBarWrapLeft: {
    position: "absolute",
    left: 12,
    top: "20%",
    bottom: "25%",
    zIndex: 15,
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 4,
  },
  verticalBarBg: {
    width: 3,
    height: 100,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.2)",
    overflow: "hidden",
    justifyContent: "flex-end",
  },
  verticalBarFill: {
    width: "100%",
    borderRadius: 2,
    backgroundColor: "#FFF",
  },
  verticalBarFillBright: {
    width: "100%",
    borderRadius: 2,
    backgroundColor: "#FFD600",
  },
  verticalBarLabel: {
    alignItems: "center",
    gap: 2,
  },
  verticalBarText: {
    color: "#FFF",
    fontSize: 11,
    fontWeight: "600",
    fontVariant: ["tabular-nums"],
  },
  doubleTapOverlay: {
    position: "absolute",
    top: "25%",
    width: "35%",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 15,
  },
  doubleTapCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  doubleTapLabel: {
    color: "#FFF",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 4,
  },
});
